services:
  - type: web
    name: collatz-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://collatz-frontend.onrender.com

  - type: web
    name: collatz-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NEXT_PUBLIC_API_URL
        value: https://collatz-api.onrender.com
